version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    environment:
      NODE_ENV: production
      PORT: 5001
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      DB_USER_USERNAME: ${DB_USER_USERNAME}
      DB_USER_PASSWORD: ${DB_USER_PASSWORD}
      DB_DATABASE_NAME: ${DB_DATABASE_NAME}
    depends_on:
      - db
    ports:
      - "5001:5001"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    environment:
      REACT_APP_API_URL: http://backend:5000
    depends_on:
      - backend
    ports:
      - "3001:80"

  db:
    image: postgres:16-alpine
    container_name: db
    environment:
      POSTGRES_USER: ${DB_USER_USERNAME}
      POSTGRES_PASSWORD: ${DB_USER_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"

volumes:
  db_data:
